// Generated by scripts/import-equipment-data.mjs.
// Armour stats: Jerp's Elden Ring Armor Optimizer, regulation 1.16 / Shadow of the Erdtree.
// Data: https://raw.githubusercontent.com/jerpdoesgames/EldenRingArmorOptimizer/2ad5e0ee88209855531a8b3ec4bf5d68bb1b0105/armor/data/armor.js
// Repository: https://github.com/jerpdoesgames/EldenRingArmorOptimizer (GPL-3.0; https://github.com/jerpdoesgames/EldenRingArmorOptimizer/blob/main/LICENSE)
// Live reference: https://jerp.tv/eldenring/armor/
// Scope: exact pieces referenced by the build armour specifications imported into app/data.ts.

export type ArmourSlot = "head" | "chest" | "arms" | "legs";
export type ArmourPiece = { name: string; slot: ArmourSlot; weight: number; poise: number };

export const EQUIPMENT_DATA_SOURCES = [
  {
    "label": "Jerp Elden Ring Armor Optimizer",
    "url": "https://jerp.tv/eldenring/armor/",
    "dataUrl": "https://raw.githubusercontent.com/jerpdoesgames/EldenRingArmorOptimizer/2ad5e0ee88209855531a8b3ec4bf5d68bb1b0105/armor/data/armor.js",
    "repositoryUrl": "https://github.com/jerpdoesgames/EldenRingArmorOptimizer",
    "licenseUrl": "https://github.com/jerpdoesgames/EldenRingArmorOptimizer/blob/main/LICENSE",
    "gameVersion": "1.16 / Shadow of the Erdtree",
    "commit": "2ad5e0ee88209855531a8b3ec4bf5d68bb1b0105"
  }
] as const;

export const ARMOUR_PIECES: readonly ArmourPiece[] = [
  {
    "name": "Alberich's Pointed Hat",
    "slot": "head",
    "weight": 1.7,
    "poise": 2
  },
  {
    "name": "Aristocrat Hat",
    "slot": "head",
    "weight": 3,
    "poise": 4
  },
  {
    "name": "Astrologer Hood",
    "slot": "head",
    "weight": 1.7,
    "poise": 3
  },
  {
    "name": "Bandit Mask",
    "slot": "head",
    "weight": 3,
    "poise": 4
  },
  {
    "name": "Banished Knight Helm",
    "slot": "head",
    "weight": 7.5,
    "poise": 11
  },
  {
    "name": "Beast Champion Helm",
    "slot": "head",
    "weight": 7.5,
    "poise": 11
  },
  {
    "name": "Black Knife Hood",
    "slot": "head",
    "weight": 3.8,
    "poise": 6
  },
  {
    "name": "Black Knight Helm",
    "slot": "head",
    "weight": 5.9,
    "poise": 9
  },
  {
    "name": "Black Wolf Mask",
    "slot": "head",
    "weight": 5.9,
    "poise": 9
  },
  {
    "name": "Bloodsoaked Mask",
    "slot": "head",
    "weight": 2.2,
    "poise": 3
  },
  {
    "name": "Blue Cloth Cowl",
    "slot": "head",
    "weight": 2.7,
    "poise": 4
  },
  {
    "name": "Bull-Goat Helm",
    "slot": "head",
    "weight": 11.3,
    "poise": 15
  },
  {
    "name": "Carian Knight Helm",
    "slot": "head",
    "weight": 4.6,
    "poise": 6
  },
  {
    "name": "Champion Headband",
    "slot": "head",
    "weight": 2.7,
    "poise": 5
  },
  {
    "name": "Confessor Hood",
    "slot": "head",
    "weight": 3.3,
    "poise": 5
  },
  {
    "name": "Consort's Mask",
    "slot": "head",
    "weight": 3.6,
    "poise": 5
  },
  {
    "name": "Crucible Axe Helm",
    "slot": "head",
    "weight": 6.6,
    "poise": 11
  },
  {
    "name": "Crucible Hammer-Helm",
    "slot": "head",
    "weight": 7.5,
    "poise": 11
  },
  {
    "name": "Cuckoo Knight Helm",
    "slot": "head",
    "weight": 5.1,
    "poise": 8
  },
  {
    "name": "Dane's Hat",
    "slot": "head",
    "weight": 2.2,
    "poise": 3
  },
  {
    "name": "Death Knight Helm",
    "slot": "head",
    "weight": 4.6,
    "poise": 7
  },
  {
    "name": "Divine Beast Helm",
    "slot": "head",
    "weight": 5.1,
    "poise": 8
  },
  {
    "name": "Divine Bird Helm",
    "slot": "head",
    "weight": 4.6,
    "poise": 8
  },
  {
    "name": "Duelist Helm",
    "slot": "head",
    "weight": 6.2,
    "poise": 10
  },
  {
    "name": "Envoy Crown",
    "slot": "head",
    "weight": 3.8,
    "poise": 4
  },
  {
    "name": "Fingerprint Helm",
    "slot": "head",
    "weight": 4.6,
    "poise": 8
  },
  {
    "name": "Fire Knight Helm",
    "slot": "head",
    "weight": 4,
    "poise": 6
  },
  {
    "name": "Gaius's Helm",
    "slot": "head",
    "weight": 8.6,
    "poise": 12
  },
  {
    "name": "Gelmir Knight Helm",
    "slot": "head",
    "weight": 5.1,
    "poise": 8
  },
  {
    "name": "Greathelm",
    "slot": "head",
    "weight": 5.9,
    "poise": 9
  },
  {
    "name": "Haima Glintstone Crown",
    "slot": "head",
    "weight": 2.7,
    "poise": 4
  },
  {
    "name": "Haligtree Knight Helm",
    "slot": "head",
    "weight": 5.1,
    "poise": 7
  },
  {
    "name": "Helm of Night",
    "slot": "head",
    "weight": 3,
    "poise": 4
  },
  {
    "name": "Helm of Solitude",
    "slot": "head",
    "weight": 10.3,
    "poise": 14
  },
  {
    "name": "High Priest Hat",
    "slot": "head",
    "weight": 1.7,
    "poise": 3
  },
  {
    "name": "Horned Warrior Helm",
    "slot": "head",
    "weight": 4.6,
    "poise": 7
  },
  {
    "name": "Iron Kasa",
    "slot": "head",
    "weight": 3.8,
    "poise": 6
  },
  {
    "name": "Jar",
    "slot": "head",
    "weight": 6.8,
    "poise": 10
  },
  {
    "name": "Knight Helm",
    "slot": "head",
    "weight": 4.6,
    "poise": 8
  },
  {
    "name": "Land of Reeds Helm",
    "slot": "head",
    "weight": 3.6,
    "poise": 5
  },
  {
    "name": "Leyndell Knight Helm",
    "slot": "head",
    "weight": 5.1,
    "poise": 8
  },
  {
    "name": "Lionel's Helm",
    "slot": "head",
    "weight": 9.1,
    "poise": 13
  },
  {
    "name": "Maliketh's Helm",
    "slot": "head",
    "weight": 5.5,
    "poise": 8
  },
  {
    "name": "Marais Mask",
    "slot": "head",
    "weight": 2.2,
    "poise": 4
  },
  {
    "name": "Mask of Confidence",
    "slot": "head",
    "weight": 3.3,
    "poise": 5
  },
  {
    "name": "Messmer's Helm",
    "slot": "head",
    "weight": 3.6,
    "poise": 5
  },
  {
    "name": "Mushroom Crown",
    "slot": "head",
    "weight": 9.1,
    "poise": 10
  },
  {
    "name": "Night's Cavalry Helm",
    "slot": "head",
    "weight": 5.5,
    "poise": 8
  },
  {
    "name": "Oathseeker Knight Helm",
    "slot": "head",
    "weight": 4.4,
    "poise": 7
  },
  {
    "name": "Okina Mask",
    "slot": "head",
    "weight": 3.6,
    "poise": 6
  },
  {
    "name": "Perfumer Hood",
    "slot": "head",
    "weight": 1.7,
    "poise": 3
  },
  {
    "name": "Preceptor's Big Hat",
    "slot": "head",
    "weight": 3.6,
    "poise": 5
  },
  {
    "name": "Prisoner Iron Mask",
    "slot": "head",
    "weight": 8.6,
    "poise": 12
  },
  {
    "name": "Prophet Blindfold",
    "slot": "head",
    "weight": 1,
    "poise": 1
  },
  {
    "name": "Pumpkin Helm",
    "slot": "head",
    "weight": 12.3,
    "poise": 11
  },
  {
    "name": "Queen's Crescent Crown",
    "slot": "head",
    "weight": 2.2,
    "poise": 3
  },
  {
    "name": "Radahn's Redmane Helm",
    "slot": "head",
    "weight": 7.5,
    "poise": 11
  },
  {
    "name": "Radiant Gold Mask",
    "slot": "head",
    "weight": 2.2,
    "poise": 3
  },
  {
    "name": "Raging Wolf Helm",
    "slot": "head",
    "weight": 4.4,
    "poise": 7
  },
  {
    "name": "Rakshasa Helm",
    "slot": "head",
    "weight": 5.5,
    "poise": 9
  },
  {
    "name": "Redmane Knight Helm",
    "slot": "head",
    "weight": 5.1,
    "poise": 8
  },
  {
    "name": "Rellana's Helm",
    "slot": "head",
    "weight": 5.1,
    "poise": 8
  },
  {
    "name": "Rotten Duelist Helm",
    "slot": "head",
    "weight": 6.4,
    "poise": 9
  },
  {
    "name": "Royal Knight Helm",
    "slot": "head",
    "weight": 6.6,
    "poise": 9
  },
  {
    "name": "Sanguine Noble Hood",
    "slot": "head",
    "weight": 1.4,
    "poise": 2
  },
  {
    "name": "Scaled Helm",
    "slot": "head",
    "weight": 6.8,
    "poise": 11
  },
  {
    "name": "Shadow Militiaman Helm",
    "slot": "head",
    "weight": 3,
    "poise": 4
  },
  {
    "name": "Silver Tear Mask",
    "slot": "head",
    "weight": 4.6,
    "poise": 6
  },
  {
    "name": "Skeletal Mask",
    "slot": "head",
    "weight": 3,
    "poise": 4
  },
  {
    "name": "Snow Witch Hat",
    "slot": "head",
    "weight": 2.2,
    "poise": 3
  },
  {
    "name": "Spellblade's Pointed Hat",
    "slot": "head",
    "weight": 1.5,
    "poise": 2
  },
  {
    "name": "St. Trina's Blossom",
    "slot": "head",
    "weight": 1,
    "poise": 2
  },
  {
    "name": "Vagabond Knight Helm",
    "slot": "head",
    "weight": 4,
    "poise": 7
  },
  {
    "name": "White Mask",
    "slot": "head",
    "weight": 3.2,
    "poise": 5
  },
  {
    "name": "Winged Serpent Helm",
    "slot": "head",
    "weight": 4.6,
    "poise": 7
  },
  {
    "name": "Zamor Mask",
    "slot": "head",
    "weight": 3.8,
    "poise": 6
  },
  {
    "name": "Alberich's Robe",
    "slot": "chest",
    "weight": 4.1,
    "poise": 7
  },
  {
    "name": "All-Knowing Armor",
    "slot": "chest",
    "weight": 10.7,
    "poise": 22
  },
  {
    "name": "Armor of Night",
    "slot": "chest",
    "weight": 7.1,
    "poise": 12
  },
  {
    "name": "Armor of Solitude",
    "slot": "chest",
    "weight": 24,
    "poise": 45
  },
  {
    "name": "Astrologer Robe",
    "slot": "chest",
    "weight": 6.3,
    "poise": 12
  },
  {
    "name": "Bandit Garb",
    "slot": "chest",
    "weight": 7.7,
    "poise": 15
  },
  {
    "name": "Banished Knight Armor",
    "slot": "chest",
    "weight": 17.5,
    "poise": 34
  },
  {
    "name": "Beast Champion Armor",
    "slot": "chest",
    "weight": 17.5,
    "poise": 34
  },
  {
    "name": "Black Knife Armor",
    "slot": "chest",
    "weight": 9.2,
    "poise": 19
  },
  {
    "name": "Black Knight Armor",
    "slot": "chest",
    "weight": 13.7,
    "poise": 28
  },
  {
    "name": "Blackflame Monk Armor",
    "slot": "chest",
    "weight": 11.8,
    "poise": 24
  },
  {
    "name": "Blaidd's Armor",
    "slot": "chest",
    "weight": 13.7,
    "poise": 28
  },
  {
    "name": "Blue Cloth Vest",
    "slot": "chest",
    "weight": 7.7,
    "poise": 16
  },
  {
    "name": "Blue Silver Mail Armor",
    "slot": "chest",
    "weight": 9.2,
    "poise": 19
  },
  {
    "name": "Bull-Goat Armor",
    "slot": "chest",
    "weight": 26.5,
    "poise": 47
  },
  {
    "name": "Carian Knight Armor",
    "slot": "chest",
    "weight": 10.4,
    "poise": 19
  },
  {
    "name": "Champion Pauldron",
    "slot": "chest",
    "weight": 5.1,
    "poise": 10
  },
  {
    "name": "Commoner's Garb",
    "slot": "chest",
    "weight": 5.1,
    "poise": 8
  },
  {
    "name": "Confessor Armor",
    "slot": "chest",
    "weight": 8.3,
    "poise": 16
  },
  {
    "name": "Crucible Axe Armor",
    "slot": "chest",
    "weight": 15.5,
    "poise": 33
  },
  {
    "name": "Crucible Tree Armor",
    "slot": "chest",
    "weight": 15.5,
    "poise": 33
  },
  {
    "name": "Death Knight Armor",
    "slot": "chest",
    "weight": 11.2,
    "poise": 22
  },
  {
    "name": "Divine Beast Warrior Armor",
    "slot": "chest",
    "weight": 10.4,
    "poise": 22
  },
  {
    "name": "Divine Bird Warrior Armor",
    "slot": "chest",
    "weight": 11.6,
    "poise": 25
  },
  {
    "name": "Finger Robe",
    "slot": "chest",
    "weight": 5.1,
    "poise": 12
  },
  {
    "name": "Fingerprint Armor",
    "slot": "chest",
    "weight": 10.6,
    "poise": 24
  },
  {
    "name": "Fire Knight Armor",
    "slot": "chest",
    "weight": 9.3,
    "poise": 19
  },
  {
    "name": "Gaius's Armor",
    "slot": "chest",
    "weight": 20.1,
    "poise": 38
  },
  {
    "name": "Gelmir Knight Armor",
    "slot": "chest",
    "weight": 11.8,
    "poise": 24
  },
  {
    "name": "Gravekeeper Cloak",
    "slot": "chest",
    "weight": 6.3,
    "poise": 12
  },
  {
    "name": "Haligtree Knight Armor",
    "slot": "chest",
    "weight": 11.8,
    "poise": 22
  },
  {
    "name": "Horned Warrior Armor",
    "slot": "chest",
    "weight": 10.4,
    "poise": 22
  },
  {
    "name": "Knight Armor",
    "slot": "chest",
    "weight": 10.6,
    "poise": 24
  },
  {
    "name": "Land of Reeds Armor",
    "slot": "chest",
    "weight": 8.3,
    "poise": 16
  },
  {
    "name": "Leda's Armor",
    "slot": "chest",
    "weight": 10.6,
    "poise": 21
  },
  {
    "name": "Leyndell Knight Armor",
    "slot": "chest",
    "weight": 11.8,
    "poise": 24
  },
  {
    "name": "Lionel's Armor",
    "slot": "chest",
    "weight": 21.2,
    "poise": 40
  },
  {
    "name": "Maliketh's Armor",
    "slot": "chest",
    "weight": 12.8,
    "poise": 24
  },
  {
    "name": "Mausoleum Knight Armor",
    "slot": "chest",
    "weight": 11.8,
    "poise": 25
  },
  {
    "name": "Messmer Soldier Armor",
    "slot": "chest",
    "weight": 9.2,
    "poise": 18
  },
  {
    "name": "Night's Cavalry Armor",
    "slot": "chest",
    "weight": 12.8,
    "poise": 25
  },
  {
    "name": "Noble's Traveling Garb",
    "slot": "chest",
    "weight": 6.3,
    "poise": 10
  },
  {
    "name": "Nox Swordstress Armor",
    "slot": "chest",
    "weight": 8.3,
    "poise": 17
  },
  {
    "name": "Oathseeker Knight Armor",
    "slot": "chest",
    "weight": 9.2,
    "poise": 19
  },
  {
    "name": "Page Garb",
    "slot": "chest",
    "weight": 5.1,
    "poise": 10
  },
  {
    "name": "Perfumer Robe",
    "slot": "chest",
    "weight": 5.1,
    "poise": 10
  },
  {
    "name": "Prisoner Clothing",
    "slot": "chest",
    "weight": 3.2,
    "poise": 5
  },
  {
    "name": "Prophet Robe",
    "slot": "chest",
    "weight": 6.3,
    "poise": 12
  },
  {
    "name": "Radahn's Lion Armor",
    "slot": "chest",
    "weight": 17.5,
    "poise": 34
  },
  {
    "name": "Raging Wolf Armor",
    "slot": "chest",
    "weight": 10.1,
    "poise": 21
  },
  {
    "name": "Rakshasa Armor",
    "slot": "chest",
    "weight": 12.8,
    "poise": 27
  },
  {
    "name": "Raptor's Black Feathers",
    "slot": "chest",
    "weight": 7.7,
    "poise": 15
  },
  {
    "name": "Redmane Knight Armor",
    "slot": "chest",
    "weight": 11.8,
    "poise": 24
  },
  {
    "name": "Rellana's Armor",
    "slot": "chest",
    "weight": 11.8,
    "poise": 24
  },
  {
    "name": "Ronin's Armor",
    "slot": "chest",
    "weight": 8.5,
    "poise": 16
  },
  {
    "name": "Rotten Gravekeeper Cloak",
    "slot": "chest",
    "weight": 6.3,
    "poise": 12
  },
  {
    "name": "Royal Knight Armor",
    "slot": "chest",
    "weight": 15.5,
    "poise": 24
  },
  {
    "name": "Royal Remains Armor",
    "slot": "chest",
    "weight": 10.6,
    "poise": 21
  },
  {
    "name": "Ruler's Robe",
    "slot": "chest",
    "weight": 5.1,
    "poise": 10
  },
  {
    "name": "Scaled Armor",
    "slot": "chest",
    "weight": 16,
    "poise": 33
  },
  {
    "name": "Shadow Militiaman Armor",
    "slot": "chest",
    "weight": 7.1,
    "poise": 13
  },
  {
    "name": "Spellblade's Traveling Attire",
    "slot": "chest",
    "weight": 3.3,
    "poise": 7
  },
  {
    "name": "Tree Surcoat",
    "slot": "chest",
    "weight": 9.2,
    "poise": 21
  },
  {
    "name": "Vagabond Knight Armor",
    "slot": "chest",
    "weight": 10.6,
    "poise": 22
  },
  {
    "name": "White Reed Armor",
    "slot": "chest",
    "weight": 8.3,
    "poise": 17
  },
  {
    "name": "Zamor Armor",
    "slot": "chest",
    "weight": 8.8,
    "poise": 18
  },
  {
    "name": "Alberich's Bracers",
    "slot": "arms",
    "weight": 1.4,
    "poise": 1
  },
  {
    "name": "All-Knowing Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 5
  },
  {
    "name": "Astrologer Gloves",
    "slot": "arms",
    "weight": 1.4,
    "poise": 2
  },
  {
    "name": "Bandit Manchettes",
    "slot": "arms",
    "weight": 1.7,
    "poise": 2
  },
  {
    "name": "Banished Knight Gauntlets",
    "slot": "arms",
    "weight": 5.8,
    "poise": 7
  },
  {
    "name": "Beast Champion Gauntlets",
    "slot": "arms",
    "weight": 5.8,
    "poise": 7
  },
  {
    "name": "Black Knife Gauntlets",
    "slot": "arms",
    "weight": 3.1,
    "poise": 4
  },
  {
    "name": "Black Knight Gauntlets",
    "slot": "arms",
    "weight": 4.6,
    "poise": 6
  },
  {
    "name": "Blaidd's Gauntlets",
    "slot": "arms",
    "weight": 4.6,
    "poise": 6
  },
  {
    "name": "Bloodsoaked Manchettes",
    "slot": "arms",
    "weight": 1.4,
    "poise": 2
  },
  {
    "name": "Bull-Goat Gauntlets",
    "slot": "arms",
    "weight": 8.8,
    "poise": 10
  },
  {
    "name": "Carian Knight Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 4
  },
  {
    "name": "Chain Gauntlets",
    "slot": "arms",
    "weight": 2.9,
    "poise": 4
  },
  {
    "name": "Champion Bracers",
    "slot": "arms",
    "weight": 2.1,
    "poise": 3
  },
  {
    "name": "Confessor Gloves",
    "slot": "arms",
    "weight": 2.8,
    "poise": 3
  },
  {
    "name": "Crucible Gauntlets",
    "slot": "arms",
    "weight": 5.2,
    "poise": 7
  },
  {
    "name": "Cuckoo Knight Gauntlets",
    "slot": "arms",
    "weight": 3.9,
    "poise": 5
  },
  {
    "name": "Death Knight Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 5
  },
  {
    "name": "Divine Bird Warrior Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 5
  },
  {
    "name": "Fingerprint Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 5
  },
  {
    "name": "Fire Knight Gauntlets",
    "slot": "arms",
    "weight": 3.1,
    "poise": 4
  },
  {
    "name": "Fire Prelate Gauntlets",
    "slot": "arms",
    "weight": 8.2,
    "poise": 10
  },
  {
    "name": "Gaius's Gauntlets",
    "slot": "arms",
    "weight": 6.7,
    "poise": 8
  },
  {
    "name": "Gauntlets of Night",
    "slot": "arms",
    "weight": 2.4,
    "poise": 3
  },
  {
    "name": "Gauntlets of Solitude",
    "slot": "arms",
    "weight": 8,
    "poise": 10
  },
  {
    "name": "Haligtree Knight Gauntlets",
    "slot": "arms",
    "weight": 3.9,
    "poise": 5
  },
  {
    "name": "Horned Warrior Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 5
  },
  {
    "name": "Knight Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 5
  },
  {
    "name": "Land of Reeds Gauntlets",
    "slot": "arms",
    "weight": 2.8,
    "poise": 3
  },
  {
    "name": "Leyndell Knight Gauntlets",
    "slot": "arms",
    "weight": 3.9,
    "poise": 5
  },
  {
    "name": "Lionel's Gauntlets",
    "slot": "arms",
    "weight": 7.1,
    "poise": 9
  },
  {
    "name": "Maliketh's Gauntlets",
    "slot": "arms",
    "weight": 4.3,
    "poise": 5
  },
  {
    "name": "Night's Cavalry Gauntlets",
    "slot": "arms",
    "weight": 4.3,
    "poise": 5
  },
  {
    "name": "Noble's Gloves",
    "slot": "arms",
    "weight": 2.1,
    "poise": 2
  },
  {
    "name": "Oathseeker Knight Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 4
  },
  {
    "name": "Perfumer Gloves",
    "slot": "arms",
    "weight": 1.4,
    "poise": 2
  },
  {
    "name": "Preceptor's Gloves",
    "slot": "arms",
    "weight": 2.1,
    "poise": 3
  },
  {
    "name": "Radahn's Gauntlets",
    "slot": "arms",
    "weight": 5.8,
    "poise": 7
  },
  {
    "name": "Raging Wolf Gauntlets",
    "slot": "arms",
    "weight": 3.4,
    "poise": 4
  },
  {
    "name": "Rakshasa Gauntlets",
    "slot": "arms",
    "weight": 4.3,
    "poise": 6
  },
  {
    "name": "Redmane Knight Gauntlets",
    "slot": "arms",
    "weight": 3.9,
    "poise": 5
  },
  {
    "name": "Rellana's Gloves",
    "slot": "arms",
    "weight": 3.9,
    "poise": 5
  },
  {
    "name": "Royal Knight Gauntlets",
    "slot": "arms",
    "weight": 5.2,
    "poise": 6
  },
  {
    "name": "Scaled Gauntlets",
    "slot": "arms",
    "weight": 5.3,
    "poise": 7
  },
  {
    "name": "Shadow Militiaman Gauntlets",
    "slot": "arms",
    "weight": 2.4,
    "poise": 3
  },
  {
    "name": "Spellblade's Gloves",
    "slot": "arms",
    "weight": 1.2,
    "poise": 1
  },
  {
    "name": "Vagabond Knight Gauntlets",
    "slot": "arms",
    "weight": 3.5,
    "poise": 5
  },
  {
    "name": "Warrior Gauntlets",
    "slot": "arms",
    "weight": 2.6,
    "poise": 3
  },
  {
    "name": "White Reed Gauntlets",
    "slot": "arms",
    "weight": 2.8,
    "poise": 4
  },
  {
    "name": "Zamor Bracelets",
    "slot": "arms",
    "weight": 2.8,
    "poise": 4
  },
  {
    "name": "Alberich's Trousers",
    "slot": "legs",
    "weight": 2.5,
    "poise": 5
  },
  {
    "name": "All-Knowing Greaves",
    "slot": "legs",
    "weight": 6.6,
    "poise": 13
  },
  {
    "name": "Astrologer Trousers",
    "slot": "legs",
    "weight": 3.9,
    "poise": 7
  },
  {
    "name": "Bandit Boots",
    "slot": "legs",
    "weight": 4.4,
    "poise": 8
  },
  {
    "name": "Banished Knight Greaves",
    "slot": "legs",
    "weight": 10.8,
    "poise": 20
  },
  {
    "name": "Beast Champion Greaves",
    "slot": "legs",
    "weight": 10.8,
    "poise": 20
  },
  {
    "name": "Black Knife Greaves",
    "slot": "legs",
    "weight": 5.7,
    "poise": 11
  },
  {
    "name": "Black Knight Greaves",
    "slot": "legs",
    "weight": 8.5,
    "poise": 17
  },
  {
    "name": "Blackflame Monk Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 14
  },
  {
    "name": "Blaidd's Greaves",
    "slot": "legs",
    "weight": 8.5,
    "poise": 17
  },
  {
    "name": "Bull-Goat Greaves",
    "slot": "legs",
    "weight": 16.4,
    "poise": 28
  },
  {
    "name": "Carian Knight Greaves",
    "slot": "legs",
    "weight": 6.6,
    "poise": 11
  },
  {
    "name": "Chain Leggings",
    "slot": "legs",
    "weight": 5.5,
    "poise": 10
  },
  {
    "name": "Champion Gaiters",
    "slot": "legs",
    "weight": 3.9,
    "poise": 4
  },
  {
    "name": "Confessor Boots",
    "slot": "legs",
    "weight": 4.8,
    "poise": 9
  },
  {
    "name": "Crucible Greaves",
    "slot": "legs",
    "weight": 9.6,
    "poise": 20
  },
  {
    "name": "Cuckoo Knight Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 14
  },
  {
    "name": "Divine Bird Warrior Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 15
  },
  {
    "name": "Duelist Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 14
  },
  {
    "name": "Fingerprint Greaves",
    "slot": "legs",
    "weight": 6.6,
    "poise": 14
  },
  {
    "name": "Fire Knight Greaves",
    "slot": "legs",
    "weight": 5.7,
    "poise": 11
  },
  {
    "name": "Fire Prelate Greaves",
    "slot": "legs",
    "weight": 15.3,
    "poise": 27
  },
  {
    "name": "Gaius's Greaves",
    "slot": "legs",
    "weight": 8.9,
    "poise": 17
  },
  {
    "name": "Gelmir Knight Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 14
  },
  {
    "name": "Greaves of Solitude",
    "slot": "legs",
    "weight": 14.8,
    "poise": 27
  },
  {
    "name": "Haligtree Knight Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 13
  },
  {
    "name": "Horned Warrior Greaves",
    "slot": "legs",
    "weight": 6.6,
    "poise": 13
  },
  {
    "name": "Knight Greaves",
    "slot": "legs",
    "weight": 6.6,
    "poise": 14
  },
  {
    "name": "Land of Reeds Greaves",
    "slot": "legs",
    "weight": 5.1,
    "poise": 10
  },
  {
    "name": "Leyndell Knight Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 14
  },
  {
    "name": "Lionel's Greaves",
    "slot": "legs",
    "weight": 13.1,
    "poise": 24
  },
  {
    "name": "Malformed Dragon Greaves",
    "slot": "legs",
    "weight": 9.9,
    "poise": 19
  },
  {
    "name": "Maliketh's Greaves",
    "slot": "legs",
    "weight": 7.9,
    "poise": 14
  },
  {
    "name": "Night's Cavalry Greaves",
    "slot": "legs",
    "weight": 7.9,
    "poise": 15
  },
  {
    "name": "Noble's Trousers",
    "slot": "legs",
    "weight": 3.9,
    "poise": 6
  },
  {
    "name": "Nox Greaves",
    "slot": "legs",
    "weight": 5.1,
    "poise": 10
  },
  {
    "name": "Oathseeker Knight Greaves",
    "slot": "legs",
    "weight": 6.6,
    "poise": 12
  },
  {
    "name": "Page Trousers",
    "slot": "legs",
    "weight": 2.5,
    "poise": 5
  },
  {
    "name": "Preceptor's Trousers",
    "slot": "legs",
    "weight": 3.9,
    "poise": 7
  },
  {
    "name": "Prisoner Trousers",
    "slot": "legs",
    "weight": 2,
    "poise": 4
  },
  {
    "name": "Prophet Trousers",
    "slot": "legs",
    "weight": 3.1,
    "poise": 3
  },
  {
    "name": "Radahn's Greaves",
    "slot": "legs",
    "weight": 10.8,
    "poise": 20
  },
  {
    "name": "Raging Wolf Greaves",
    "slot": "legs",
    "weight": 6.3,
    "poise": 12
  },
  {
    "name": "Rakshasa Greaves",
    "slot": "legs",
    "weight": 7.9,
    "poise": 16
  },
  {
    "name": "Redmane Knight Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 14
  },
  {
    "name": "Rellana's Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 14
  },
  {
    "name": "Ronin's Greaves",
    "slot": "legs",
    "weight": 5.7,
    "poise": 11
  },
  {
    "name": "Rotten Duelist Greaves",
    "slot": "legs",
    "weight": 7.3,
    "poise": 13
  },
  {
    "name": "Royal Knight Greaves",
    "slot": "legs",
    "weight": 9.6,
    "poise": 14
  },
  {
    "name": "Royal Remains Greaves",
    "slot": "legs",
    "weight": 6.6,
    "poise": 12
  },
  {
    "name": "Scaled Greaves",
    "slot": "legs",
    "weight": 9.9,
    "poise": 20
  },
  {
    "name": "Shadow Militiaman Greaves",
    "slot": "legs",
    "weight": 4.4,
    "poise": 8
  },
  {
    "name": "Spellblade's Trousers",
    "slot": "legs",
    "weight": 2.6,
    "poise": 5
  },
  {
    "name": "Vagabond Knight Greaves",
    "slot": "legs",
    "weight": 5.7,
    "poise": 12
  },
  {
    "name": "Warrior Greaves",
    "slot": "legs",
    "weight": 4.8,
    "poise": 10
  },
  {
    "name": "White Reed Greaves",
    "slot": "legs",
    "weight": 5.1,
    "poise": 10
  },
  {
    "name": "Zamor Legwraps",
    "slot": "legs",
    "weight": 5.1,
    "poise": 10
  }
];

export const ARMOUR_SET_ALIASES: Readonly<Record<string, readonly string[]>> = {
  "Vagabond starting armour": [
    "Vagabond Knight Helm",
    "Vagabond Knight Armor",
    "Vagabond Knight Gauntlets",
    "Vagabond Knight Greaves"
  ],
  "Warrior starting armour": [
    "Blue Cloth Cowl",
    "Blue Cloth Vest",
    "Warrior Gauntlets",
    "Warrior Greaves"
  ],
  "Hero starting armour": [
    "Champion Headband",
    "Champion Pauldron",
    "Champion Bracers",
    "Champion Gaiters"
  ],
  "Bandit starting armour": [
    "Bandit Mask",
    "Bandit Garb",
    "Bandit Manchettes",
    "Bandit Boots"
  ],
  "Astrologer starting armour": [
    "Astrologer Hood",
    "Astrologer Robe",
    "Astrologer Gloves",
    "Astrologer Trousers"
  ],
  "Prophet starting armour": [
    "Prophet Blindfold",
    "Prophet Robe",
    "Prophet Trousers"
  ],
  "Samurai starting armour": [
    "Land of Reeds Helm",
    "Land of Reeds Armor",
    "Land of Reeds Gauntlets",
    "Land of Reeds Greaves"
  ],
  "Prisoner starting armour": [
    "Prisoner Iron Mask",
    "Prisoner Clothing",
    "Prisoner Trousers"
  ],
  "Confessor starting armour": [
    "Confessor Hood",
    "Confessor Armor",
    "Confessor Gloves",
    "Confessor Boots"
  ],
  "Alberich's Set": [
    "Alberich's Pointed Hat",
    "Alberich's Robe",
    "Alberich's Bracers",
    "Alberich's Trousers"
  ],
  "Spellblade Set": [
    "Spellblade's Pointed Hat",
    "Spellblade's Traveling Attire",
    "Spellblade's Gloves",
    "Spellblade's Trousers"
  ],
  "Spellblades Set": [
    "Spellblade's Pointed Hat",
    "Spellblade's Traveling Attire",
    "Spellblade's Gloves",
    "Spellblade's Trousers"
  ],
  "Banished Knight Set": [
    "Banished Knight Helm",
    "Banished Knight Armor",
    "Banished Knight Gauntlets",
    "Banished Knight Greaves"
  ],
  "Beast Champion Set": [
    "Beast Champion Helm",
    "Beast Champion Armor",
    "Beast Champion Gauntlets",
    "Beast Champion Greaves"
  ],
  "Black Knife Set": [
    "Black Knife Hood",
    "Black Knife Armor",
    "Black Knife Gauntlets",
    "Black Knife Greaves"
  ],
  "Black Knight Set": [
    "Black Knight Helm",
    "Black Knight Armor",
    "Black Knight Gauntlets",
    "Black Knight Greaves"
  ],
  "Bull-Goat Set": [
    "Bull-Goat Helm",
    "Bull-Goat Armor",
    "Bull-Goat Gauntlets",
    "Bull-Goat Greaves"
  ],
  "Carian Knight Set": [
    "Carian Knight Helm",
    "Carian Knight Armor",
    "Carian Knight Gauntlets",
    "Carian Knight Greaves"
  ],
  "Leyndell Knight Set": [
    "Leyndell Knight Helm",
    "Leyndell Knight Armor",
    "Leyndell Knight Gauntlets",
    "Leyndell Knight Greaves"
  ],
  "Crucible Axe Set": [
    "Crucible Axe Helm",
    "Crucible Axe Armor",
    "Crucible Gauntlets",
    "Crucible Greaves"
  ],
  "Divine Bird Set": [
    "Divine Bird Helm",
    "Divine Bird Warrior Armor",
    "Divine Bird Warrior Gauntlets",
    "Divine Bird Warrior Greaves"
  ],
  "Fingerprint Set": [
    "Fingerprint Helm",
    "Fingerprint Armor",
    "Fingerprint Gauntlets",
    "Fingerprint Greaves"
  ],
  "Gaius's Set": [
    "Gaius's Helm",
    "Gaius's Armor",
    "Gaius's Gauntlets",
    "Gaius's Greaves"
  ],
  "General Radahn Set": [
    "Radahn's Redmane Helm",
    "Radahn's Lion Armor",
    "Radahn's Gauntlets",
    "Radahn's Greaves"
  ],
  "Haligtree Knight Set": [
    "Haligtree Knight Helm",
    "Haligtree Knight Armor",
    "Haligtree Knight Gauntlets",
    "Haligtree Knight Greaves"
  ],
  "Knight Set": [
    "Knight Helm",
    "Knight Armor",
    "Knight Gauntlets",
    "Knight Greaves"
  ],
  "Maliketh's Set": [
    "Maliketh's Helm",
    "Maliketh's Armor",
    "Maliketh's Gauntlets",
    "Maliketh's Greaves"
  ],
  "Land of Reeds Set": [
    "Land of Reeds Helm",
    "Land of Reeds Armor",
    "Land of Reeds Gauntlets",
    "Land of Reeds Greaves"
  ],
  "Lionel's Set": [
    "Lionel's Helm",
    "Lionel's Armor",
    "Lionel's Gauntlets",
    "Lionel's Greaves"
  ],
  "Night's Cavalry Set": [
    "Night's Cavalry Helm",
    "Night's Cavalry Armor",
    "Night's Cavalry Gauntlets",
    "Night's Cavalry Greaves"
  ],
  "Oathseeker Knight Set": [
    "Oathseeker Knight Helm",
    "Oathseeker Knight Armor",
    "Oathseeker Knight Gauntlets",
    "Oathseeker Knight Greaves"
  ],
  "Raging Wolf Set": [
    "Raging Wolf Helm",
    "Raging Wolf Armor",
    "Raging Wolf Gauntlets",
    "Raging Wolf Greaves"
  ],
  "Blaidd's Set": [
    "Black Wolf Mask",
    "Blaidd's Armor",
    "Blaidd's Gauntlets",
    "Blaidd's Greaves"
  ],
  "Rakshasa Set": [
    "Rakshasa Helm",
    "Rakshasa Armor",
    "Rakshasa Gauntlets",
    "Rakshasa Greaves"
  ],
  "Redmane Knight Set": [
    "Redmane Knight Helm",
    "Redmane Knight Armor",
    "Redmane Knight Gauntlets",
    "Redmane Knight Greaves"
  ],
  "Rellana's Set": [
    "Rellana's Helm",
    "Rellana's Armor",
    "Rellana's Gloves",
    "Rellana's Greaves"
  ],
  "Royal Knight Set": [
    "Royal Knight Helm",
    "Royal Knight Armor",
    "Royal Knight Gauntlets",
    "Royal Knight Greaves"
  ],
  "Scaled Armor Set": [
    "Scaled Helm",
    "Scaled Armor",
    "Scaled Gauntlets",
    "Scaled Greaves"
  ],
  "Scaled Set": [
    "Scaled Helm",
    "Scaled Armor",
    "Scaled Gauntlets",
    "Scaled Greaves"
  ],
  "Shadow Militiaman Set": [
    "Shadow Militiaman Helm",
    "Shadow Militiaman Armor",
    "Shadow Militiaman Gauntlets",
    "Shadow Militiaman Greaves"
  ],
  "Solitude Set": [
    "Helm of Solitude",
    "Armor of Solitude",
    "Gauntlets of Solitude",
    "Greaves of Solitude"
  ],
  "White Reed Set": [
    "Okina Mask",
    "White Reed Armor",
    "White Reed Gauntlets",
    "White Reed Greaves"
  ],
  "Zamor Set": [
    "Zamor Mask",
    "Zamor Armor",
    "Zamor Bracelets",
    "Zamor Legwraps"
  ]
};

export const ARMOUR_NAME_ALIASES: Readonly<Record<string, string>> = {
  "Jar helm": "Jar",
  "Great Helm": "Greathelm",
  "Tree Coat": "Tree Surcoat",
  "Chain Gloves": "Chain Gauntlets",
  "Chain Greaves": "Chain Leggings",
  "Bull-Goats Gaunlets": "Bull-Goat Gauntlets",
  "Noble's Glove": "Noble's Gloves"
};

const NORMALIZED_GENERIC_ARMOUR = [
  {
    "source": "^n\\/?a\\b",
    "flags": "i"
  },
  {
    "source": "not specified",
    "flags": "i"
  },
  {
    "source": "cosmetic .* character",
    "flags": "i"
  },
  {
    "source": "no specific armou?r",
    "flags": "i"
  },
  {
    "source": "^(?:(?:the|they)\\s+)?(?:any|heaviest|light|little or no)\\b",
    "flags": "i"
  },
  {
    "source": "allows? (?:you )?to (?:medium|med|mid|light|fast) roll",
    "flags": "i"
  },
  {
    "source": "high poise",
    "flags": "i"
  },
  {
    "source": "high protection",
    "flags": "i"
  }
].map(({ source, flags }) => new RegExp(source, flags));
const normalizeArmourText = (value: string) => value.normalize("NFKD").replace(/[’‘]/g, "'").toLowerCase().replace(/[^a-z0-9']+/g, " ").replace(/\s+/g, " ").trim();
const phraseIndex = (source: string, phrase: string) => (` ${source} `).indexOf(` ${phrase} `);
export const ARMOUR_PIECE_BY_NAME = new Map(ARMOUR_PIECES.map((piece) => [piece.name, piece]));

/** Splits source prose into canonical Jerp armour pieces, expanding named sets and ignoring generic roll advice. */
export function splitArmourSpecification(value: string): ArmourPiece[] {
  const source = normalizeArmourText(value);
  if (!source) return [];
  const candidates: Array<{ names: readonly string[]; index: number; length: number }> = [];
  for (const piece of ARMOUR_PIECES) { const phrase = normalizeArmourText(piece.name); const index = phraseIndex(source, phrase); if (index >= 0) candidates.push({ names: [piece.name], index, length: phrase.length }); }
  for (const [alias, name] of Object.entries(ARMOUR_NAME_ALIASES)) { const phrase = normalizeArmourText(alias); const index = phraseIndex(source, phrase); if (index >= 0) candidates.push({ names: [name], index, length: phrase.length }); }
  for (const [alias, names] of Object.entries(ARMOUR_SET_ALIASES)) { const phrase = normalizeArmourText(alias); const index = phraseIndex(source, phrase); if (index >= 0) candidates.push({ names, index, length: phrase.length }); }
  const selected = candidates.sort((a, b) => b.length - a.length || a.index - b.index).filter((candidate, position, sorted) => !sorted.slice(0, position).some((other) => other.index < candidate.index + candidate.length && candidate.index < other.index + other.length));
  const matches = selected.sort((a, b) => a.index - b.index).flatMap((match) => match.names.map((name, slotOffset) => ({ name, index: match.index + slotOffset / 10 })));
  const ordered = [...new Map(matches.map((match) => [match.name, match])).values()];
  return ordered.map(({ name }) => ARMOUR_PIECE_BY_NAME.get(name)).filter((piece): piece is ArmourPiece => Boolean(piece));
}

/** True only when a specification contains no named equipment and is generic/N/A prose. */
export function isGenericArmourSpecification(value: string): boolean {
  return splitArmourSpecification(value).length === 0 && NORMALIZED_GENERIC_ARMOUR.some((pattern) => pattern.test(value.trim()));
}
