import type { Build } from "./data";

const unavailable = (level: string, weapon: string, availableFrom: "early" | "mid" | "late" | "dlc") => {
  const phases = { early: `Published from ${level}`, mid: `Published from ${level}`, late: `Published from ${level}`, dlc: `Published from ${level}` };
  const order = ["early", "mid", "late", "dlc"] as const;
  for (const phase of order.slice(order.indexOf(availableFrom))) phases[phase] = weapon;
  return phases;
};

export const sourcedMemeBuilds: Build[] = [
  {
    id: "meme-let-me-solo-her",
    name: "Let Me Solo Her",
    stats: "DEX / ARC / END",
    role: "Published community build",
    playstyle: "KleinTsuboiOW's published Malenia setup: two status katanas, a jar helm and no body armour.",
    complexity: "Published guide",
    phases: unavailable("late game", "Cold Uchigatana + Rivers of Blood", "late"),
    tags: ["meme", "cosplay", "katana", "bleed", "frost"],
    startingClass: "Wretch",
    mechanic: "Status buildup",
    collection: "Meme / cosplay",
    availableFrom: "late",
    publishedLoadout: {
      level: "Late game",
      weapon: "Cold Uchigatana (right hand)",
      offhand: "Rivers of Blood (left hand)",
      skill: "Hoarfrost Stomp",
      talismans: ["Not specified by source"],
      armour: "Jar helm only; no body armour",
      spells: [],
      flask: "Not specified by source",
      stats: "Prioritise Dexterity, Arcane and Stamina; the source does not give exact values.",
    },
    source: { label: "PC Gamer: Let Me Solo Her's build", url: "https://www.pcgamer.com/best-elden-ring-build/" },
  },
  {
    id: "meme-sonic-lightning-ram",
    name: "Sonic Lightning Ram",
    stats: "Source stats",
    role: "Published meme build",
    playstyle: "The documented Sonic meme build is built around repeatedly attacking with the Lightning Ram roll.",
    complexity: "Published guide",
    phases: unavailable("Altus Plateau", "Lightning Ram-compatible weapon", "mid"),
    tags: ["meme", "sonic", "lightning", "rolling"],
    startingClass: "Not specified",
    mechanic: "Skill damage",
    collection: "Meme / cosplay",
    availableFrom: "mid",
    publishedLoadout: {
      level: "Available in Altus Plateau",
      weapon: "Any weapon compatible with Lightning Ram",
      offhand: "Not specified by source",
      skill: "Lightning Ram",
      talismans: ["Not specified by source"],
      armour: "Cosmetic Sonic character; equipment not specified",
      spells: [],
      flask: "Not specified by source",
      stats: "The source recommends enough FP and stamina to keep rolling; no exact values are supplied.",
    },
    source: { label: "Inverse: Elden Ring Sonic build", url: "https://www.inverse.com/gaming/elden-ring-sonic-build-roll-hedgehog" },
  },
  {
    id: "meme-minecraft-steve",
    name: "Minecraft Steve",
    stats: "Source stats",
    role: "Published cosplay build",
    playstyle: "A published community cosplay using a Pickaxe coloured blue with magic grease or Scholar's Armament.",
    complexity: "Published guide",
    phases: unavailable("early game", "Pickaxe", "early"),
    tags: ["meme", "cosplay", "minecraft", "pickaxe"],
    startingClass: "Not specified",
    mechanic: "Charged attacks",
    collection: "Meme / cosplay",
    availableFrom: "early",
    publishedLoadout: {
      level: "Early game",
      weapon: "Pickaxe",
      offhand: "Magic Grease or a staff for Scholar's Armament",
      skill: "Scholar's Armament or Magic Grease for the blue 'diamond pickaxe' effect",
      talismans: ["Not specified by source"],
      armour: "Not specified by source",
      spells: ["Scholar's Armament (optional alternative to Magic Grease)"],
      flask: "Not specified by source",
      stats: "Not specified by source",
    },
    source: { label: "r/EldenRingBuilds: Minecraft Steve cosplay", url: "https://www.reddit.com/r/EldenRingBuilds/comments/1jk0urc/ideas_for_cosplay_builds/" },
  },
  {
    id: "meme-soldier-of-godrick",
    name: "Soldier of God, Rick",
    stats: "Source stats",
    role: "Published cosplay build",
    playstyle: "A first-hour Godrick Soldier cosplay with only ordinary soldier equipment and consumables.",
    complexity: "Published guide",
    phases: unavailable("first hour", "Lordsworn weapon (source author uses War Pick)", "early"),
    tags: ["meme", "cosplay", "godrick", "soldier"],
    startingClass: "Not specified",
    mechanic: "Guard counters",
    collection: "Meme / cosplay",
    availableFrom: "early",
    publishedLoadout: {
      level: "First hour / all game",
      weapon: "Any Lordsworn weapon; source author uses War Pick",
      offhand: "Brass Shield, Torch and Crossbow",
      skill: "Use only the listed soldier equipment",
      talismans: ["Not specified by source"],
      armour: "Not specified by source",
      spells: [],
      flask: "Not specified by source",
      stats: "Not specified by source",
    },
    source: { label: "r/Eldenring: Godrick Soldier cosplay", url: "https://www.reddit.com/r/Eldenring/comments/1llxkkh/what_are_the_best_cosplay_builds_youve_seen_or/" },
  },
  {
    id: "meme-bubble-boy",
    name: "Envoy Bubble Boy",
    stats: "Source stats",
    role: "Published meme build",
    playstyle: "A documented Envoy cosplay using all three horns and the Envoy Crown, including the Long Horn's Bubble Shower.",
    complexity: "Published guide",
    phases: unavailable("late game / NG+", "Envoy's Long Horn + Envoy's Greathorn", "late"),
    tags: ["meme", "bubble", "envoy", "horn"],
    startingClass: "Not specified",
    mechanic: "Skill damage",
    collection: "Meme / cosplay",
    availableFrom: "late",
    publishedLoadout: {
      level: "Late game / NG+",
      weapon: "Envoy's Long Horn and Envoy's Greathorn",
      offhand: "Envoy's Horn",
      skill: "Bubble Shower and Great Oracular Bubble",
      talismans: ["Not specified by source"],
      armour: "Envoy Crown; remaining armour not specified",
      spells: [],
      flask: "Not specified by source",
      stats: "Not specified by source",
    },
    source: { label: "r/Eldenring: Envoy bubble build", url: "https://www.reddit.com/r/Eldenring/comments/1th7wtx/ive_done_almost_every_build_what_build_should_i_do/" },
  },
  {
    id: "meme-jar-jar",
    name: "Jar Jar",
    stats: "STR",
    role: "Published community build",
    playstyle: "A published RL150 warrior-jar setup combining fists, a jar shield, cannon, throwing pots and perfumes.",
    complexity: "Published guide",
    phases: unavailable("RL150", "Heavy Star Fist + Jar Cannon", "late"),
    tags: ["meme", "jar", "cannon", "strength"],
    startingClass: "Not specified",
    mechanic: "Skill damage",
    collection: "Meme / cosplay",
    availableFrom: "late",
    publishedLoadout: {
      level: "RL150",
      weapon: "Heavy Star Fist +25 with Hoarah Loux's Earthshaker; Jar Cannon +10",
      offhand: "Beastman's Jar-Shield +25 (No Skill); Finger Seal +25",
      skill: "Hoarah Loux's Earthshaker; Fire, Volcano and Fire Giant pots; Ironjar and Bloodboil perfumes",
      talismans: ["Great-Jar's Arsenal", "Companion Jar", "Shard of Alexander", "Godfrey Icon"],
      armour: "Jar helm + Lionel's Armor",
      spells: ["Flame, Grant Me Strength", "Bestial Vitality", "Golden Vow"],
      flask: "Not specified by source",
      stats: "Level 150 Strength build; exact stat spread not specified in the post.",
    },
    source: { label: "r/EldenRingBuilds: Jar Jar RL150", url: "https://www.reddit.com/r/EldenRingBuilds/comments/176b6np/elden_ring_build_jar_jar_lvl_150_strength_build/" },
  },
];
