import type { Build } from "./data";

const unavailable = (level: string, weapon: string, availableFrom: "early" | "mid" | "late" | "dlc") => {
  const phases = { early: `Published from ${level}`, mid: `Published from ${level}`, late: `Published from ${level}`, dlc: `Published from ${level}` };
  const order = ["early", "mid", "late", "dlc"] as const;
  for (const phase of order.slice(order.indexOf(availableFrom))) phases[phase] = weapon;
  return phases;
};

export const sourcedMemeBuilds: Build[] = [
  {
    id: "meme-let-me-solo-her",
    name: "Let Me Solo Her",
    stats: "DEX / ARC / END",
    role: "Published community build",
    playstyle: "KleinTsuboiOW's recipe is bare: a Cold Uchigatana in the right hand with Hoarfrost Stomp, Rivers of Blood in the left, and a jar helm with no other armour. The fight runs on two status clocks — Hoarfrost Stomp procs Frostbite with frost bursts while the twin-katana power stance and Corpse Piler's blood waves stack hemorrhage between dodges. PC Gamer credits a substantial stamina bar for chains of evades, so Dexterity, Arcane and Stamina lead; the magazine only speculates that spare Intelligence deepens the frost damage. Ordinary enemies fall to a frost opener and power-stance flurries, but against Malenia every plan is identical: read the attack, dodge late, punish recovery, repeat. The honest limitation is that none of this gear beats her for you, since those wins came from hundreds of reps and duelling her solo as a co-op phantom means an enlarged health pool. Exact stats, talismans and flasks were never published, and the 2022 clips predate later balance changes to Hoarfrost Stomp and Corpse Piler, so expect slower results than the footage implies.",
    complexity: "Published guide",
    phases: unavailable("late game", "Cold Uchigatana + Rivers of Blood", "late"),
    tags: ["meme", "cosplay", "katana", "bleed", "frost"],
    startingClass: "Wretch",
    mechanic: "Status buildup",
    collection: "Meme / cosplay",
    availableFrom: "late",
    publishedLoadout: {
      level: "Late game",
      weapon: "Cold Uchigatana (right hand)",
      offhand: "Rivers of Blood (left hand)",
      skill: "Hoarfrost Stomp",
      talismans: ["Not specified by source"],
      armour: "Jar helm only; no body armour",
      spells: [],
      flask: "Not specified by source",
      stats: "Prioritise Dexterity, Arcane and Stamina; the source does not give exact values.",
    },
    source: { label: "PC Gamer: Let Me Solo Her's build", url: "https://www.pcgamer.com/best-elden-ring-build/" },
  },
  {
    id: "meme-sonic-lightning-ram",
    name: "Sonic Lightning Ram",
    stats: "Source stats",
    role: "Published meme build",
    playstyle: "Everything hangs on one Ash of War. Lightning Ram comes from a scarab east of Stormcaller Church on the Altus Plateau; applied to a compatible weapon, L2 sends you tumbling forward as an electrified wheel, paying FP to start and stamina per tumble until a bar runs dry. The loop Inverse filmed is pure PvP pressure: charge straight into an opponent, because contact stuns them before they can swing back, then keep rolling through them until the health bar melts. Ordinary mobs can be bowled over the same way, though the article is blunt that large bosses resist the stun, so PvE is safer with conventional hits between rolls. Every attempt starts point-blank, meaning a whiffed roll leaves you exposed mid-animation with no melee answer. Invest in FP and stamina to lengthen the spam; the source offers no class, talismans or armour plan beyond an optional, stats-free Sonic look in the character creator. Its \"shockingly overpowered\" verdict is a March 2022 snapshot, and Inverse itself predicted a nerf, so treat the power claims as dated rather than current.",
    complexity: "Published guide",
    phases: unavailable("Altus Plateau", "Lightning Ram-compatible weapon", "mid"),
    tags: ["meme", "sonic", "lightning", "rolling"],
    startingClass: "Not specified",
    mechanic: "Skill damage",
    collection: "Meme / cosplay",
    availableFrom: "mid",
    publishedLoadout: {
      level: "Available in Altus Plateau",
      weapon: "Any weapon compatible with Lightning Ram",
      offhand: "Not specified by source",
      skill: "Lightning Ram",
      talismans: ["Not specified by source"],
      armour: "Cosmetic Sonic character; equipment not specified",
      spells: [],
      flask: "Not specified by source",
      stats: "The source recommends enough FP and stamina to keep rolling; no exact values are supplied.",
    },
    source: { label: "Inverse: Elden Ring Sonic build", url: "https://www.inverse.com/gaming/elden-ring-sonic-build-roll-hedgehog" },
  },
  {
    id: "meme-minecraft-steve",
    name: "Minecraft Steve",
    stats: "Source stats",
    role: "Published cosplay build",
    playstyle: "The joke is one layer deep: Minecraft Steve mines with a diamond pickaxe, and the Lands Between supplies the paint. The kit is the Pickaxe farmed from Limgrave's miners, swung two-handed and tinted blue by Magic Grease between fights or by Scholar's Armament cast from a staff for a lasting sheen. Under the cosplay it is a genuinely strange weapon, a great-hammer-class tool that deals pierce damage, carries heavy stance damage for posture breaks, and swings a distinctive charged overhead that reads like breaking blocks. Because the Pickaxe accepts Ash of War affinities and external buffs, the blue tint coexists with any serious infusion you build around it. The honest loop in a normal fight is patient: bait a swing, step or block out of range, and answer with heavy hits or the charged R2, since a tool this slow cannot out-trade fast weapons. The Reddit source is a single line in a cosplay-ideas thread, so class, stats, armour, talismans and boss tactics are simply not stated; the diamond-blue gimmick is the entire citation, and everything beyond it is your own roleplay choice.",
    complexity: "Published guide",
    phases: unavailable("early game", "Pickaxe", "early"),
    tags: ["meme", "cosplay", "minecraft", "pickaxe"],
    startingClass: "Not specified",
    mechanic: "Charged attacks",
    collection: "Meme / cosplay",
    availableFrom: "early",
    publishedLoadout: {
      level: "Early game",
      weapon: "Pickaxe",
      offhand: "Magic Grease or a staff for Scholar's Armament",
      skill: "Scholar's Armament or Magic Grease for the blue 'diamond pickaxe' effect",
      talismans: ["Not specified by source"],
      armour: "Not specified by source",
      spells: ["Scholar's Armament (optional alternative to Magic Grease)"],
      flask: "Not specified by source",
      stats: "Not specified by source",
    },
    source: { label: "r/EldenRingBuilds: Minecraft Steve cosplay", url: "https://www.reddit.com/r/EldenRingBuilds/comments/1jk0urc/ideas_for_cosplay_builds/" },
  },
  {
    id: "meme-soldier-of-godrick",
    name: "Soldier of God, Rick",
    stats: "Source stats",
    role: "Published cosplay build",
    playstyle: "The premise is a full-game hostage run: you are one of Godrick's rank-and-file, so every tool must be something his first-hour garrison could plausibly carry. The kit is a Warpick backed by a Brass Shield, a crossbow for ranged picks, Fire Pots for clustered enemies, and Godrick Soldier Ashes summoning a comrade with the same hammer-and-crossbow pairing. Combat is textbook shield discipline: raise the Brass Shield, absorb or sidestep a strike, answer with the Warpick, take guard counters when the window opens, swapping to the crossbow when closing the gap is suicide. Camps play as miniature sieges: pot the clumps, let the summon hold aggro, execute stragglers, while bosses become attrition fights with no upgraded weapon to rescue you. That low ceiling is the whole meme: late-game wins are bought with spacing, block timing and composure rather than scaling. The Reddit thread behind this entry is a reader recommendation with no stat spread, talismans, armour list or flask advice attached, so treat the kit above as the poster's account rather than a documented spec sheet.",
    complexity: "Published guide",
    phases: unavailable("first hour", "Lordsworn weapon (source author uses War Pick)", "early"),
    tags: ["meme", "cosplay", "godrick", "soldier"],
    startingClass: "Not specified",
    mechanic: "Guard counters",
    collection: "Meme / cosplay",
    availableFrom: "early",
    publishedLoadout: {
      level: "First hour / all game",
      weapon: "Warpick",
      offhand: "Brass Shield, Torch and Crossbow",
      skill: "Default Warpick skill; Fire Pots and Godrick Soldier Ashes for utility",
      talismans: ["Not specified by source"],
      armour: "Not specified by source",
      spells: [],
      flask: "Not specified by source",
      stats: "Not specified by source",
    },
    source: { label: "r/Eldenring: Godrick Soldier cosplay", url: "https://www.reddit.com/r/Eldenring/comments/1llxkkh/what_are_the_best_cosplay_builds_youve_seen_or/" },
  },
  {
    id: "meme-bubble-boy",
    name: "Envoy Bubble Boy",
    stats: "Source stats",
    role: "Published meme build",
    playstyle: "Oracle Envoys attack by blowing bubbles, so this build exists to do that on purpose. You rotate three horns — Envoy's Long Horn and Envoy's Greathorn main-hand, the small Envoy's Horn off-hand — each with its own skill: Bubble Shower sprays a drifting cloud of holy projectiles, Great Oracular Bubble lobs one heavy shot, Oracular Bubble is the little horn's compact version. Between casts the horns are slow holy melee weapons, so fights are about planting your feet, firing from safety and resetting before anything closes distance. The Envoy Crown is the one armour piece doing mechanical work, strengthening envoy weapon skills; the rest of the outfit is unspecified. The full cosplay only assembles late, its pieces split between Leyndell and Miquella's Haligtree, and each horn wants its own Somber smithing stones. The honest catch is that Bubble Shower's damage and poise damage were cut in modern patches, so old clips of bubbles shredding bosses overstate what you will feel today. The Reddit citation is a one-sentence suggestion, so stats, talismans and flasks remain your own call.",
    complexity: "Published guide",
    phases: unavailable("late game", "Envoy's Long Horn + Envoy's Greathorn", "late"),
    tags: ["meme", "bubble", "envoy", "horn"],
    startingClass: "Not specified",
    mechanic: "Skill damage",
    collection: "Meme / cosplay",
    availableFrom: "late",
    publishedLoadout: {
      level: "Late game",
      weapon: "Envoy's Long Horn and Envoy's Greathorn",
      offhand: "Envoy's Horn",
      skill: "Oracular Bubble, Bubble Shower and Great Oracular Bubble",
      talismans: ["Not specified by source"],
      armour: "Envoy Crown; remaining armour not specified",
      spells: [],
      flask: "Not specified by source",
      stats: "Not specified by source",
    },
    source: { label: "r/Eldenring: Envoy bubble build", url: "https://www.reddit.com/r/Eldenring/comments/1th7wtx/ive_done_almost_every_build_what_build_should_i_do/" },
  },
  {
    id: "meme-jar-jar",
    name: "Jar Jar",
    stats: "STR",
    role: "Published community build",
    playstyle: "This RL150 Strength cosplay puts the jar theme in every slot: Heavy Star Fist +25 with Hoarah Loux's Earthshaker as the damage engine, Jar Cannon +10 for the opening greatbolt, Beastman's Jar-Shield +25 with No Skill off-hand, and a Finger Seal +25 for buffs. Fights open at range: Golden Vow and Flame, Grant Me Strength, one cannon shot, then close behind the shield into light fist strings, keeping Earthshaker as the committed posture-breaker for a nearly full poise bar. The talismans do real math: Great-Jar's Arsenal makes jar-plus-Lionel plate wearable, Shard of Alexander amplifies Earthshaker, Two-Headed Turtle feeds the stamina-hungry fists, and Companion Jar boosts the thrown Fire, Volcano and Fire Giant pots; Ironjar and Bloodboil aromatics are situational spikes. Bestial Vitality patches the health you bleed reaching melee range. The post flags a design casualty: Godfrey Icon would be a dead slot because Earthshaker cannot be charged, so it is omitted. Beyond \"Strength, level 150\" no stat spread is published, and fist range means every mistake lands at hugging distance.",
    complexity: "Published guide",
    phases: unavailable("RL150", "Heavy Star Fist + Jar Cannon", "late"),
    tags: ["meme", "jar", "cannon", "strength"],
    startingClass: "Not specified",
    mechanic: "Skill damage",
    collection: "Meme / cosplay",
    availableFrom: "late",
    publishedLoadout: {
      level: "RL150",
      weapon: "Heavy Star Fist +25 with Hoarah Loux's Earthshaker; Jar Cannon +10",
      offhand: "Beastman's Jar-Shield +25 (No Skill); Finger Seal +25",
      skill: "Hoarah Loux's Earthshaker; Fire, Volcano and Fire Giant pots; Ironjar and Bloodboil perfumes",
      talismans: ["Great-Jar's Arsenal", "Companion Jar", "Shard of Alexander", "Two-Headed Turtle Talisman"],
      armour: "Jar helm + Lionel's Armor",
      spells: ["Flame, Grant Me Strength", "Bestial Vitality", "Golden Vow"],
      flask: "Not specified by source",
      stats: "Level 150 Strength build; exact stat spread not specified in the post.",
    },
    source: { label: "r/EldenRingBuilds: Jar Jar RL150", url: "https://www.reddit.com/r/EldenRingBuilds/comments/176b6np/elden_ring_build_jar_jar_lvl_150_strength_build/" },
  },
];
