import type { Build, StageLoadout } from "./data";

const sourcedStage = (level: string, weapon: string, offhand: string, skill: string, talismans: string[], armour: string, spells: string[], flask: string, stats: string): Omit<StageLoadout, "talismanSlots"> => ({ level, weapon, offhand, skill, talismans, armour, spells, flask, stats });

export const additionalSourcedBuilds: Build[] = [
  {
    id: "mobalytics-bloodhounds-fang",
    name: "Bloodhound’s Fang Finesse",
    stats: "STR / DEX / FAI",
    role: "Melee",
    playstyle: "Two-hand the Fang and anchor fights on jumping attacks: jump heavies out-hit other curved greatswords, build stance damage, and cost no FP, so field play is running lights and jump heavies with Finesse banked for openings. The skill slashes upward and flings you clear; the heavy follow-up Bloodhound’s Steps back in with invulnerability frames — versus bosses, jump-heavy the opener, Finesse out when the boss stirs, bait, then dash through the swing. Shard of Alexander scales both skill halves, Green Turtle refills the drained stamina, and Ritual Sword Talisman pays at full HP — Opaline Bubbletear helps keep it there. Bloodflame Blade plus Flame, Grant Me Strength go up before hard fights: fire and delayed blood loss stack on the innate 55 buildup, the incantation lifts physical and fire, and both reapply at phase transitions. The full skill drains FP and stamina, so don’t chain it on cooldown, and mind your backdrop — the backward leap can dump you into walls or off cliffs. Bleed-immune targets gut the proc, but raw physical holds up and a grease or elemental swap keeps the edge.",
    complexity: "Published guide",
    phases: { early: "Uchigatana → Bloodhound’s Fang", mid: "Bloodhound’s Fang + Bloodflame Blade", late: "Bloodhound’s Fang + Finesse", dlc: "Bloodhound’s Fang + Finesse" },
    tags: ["bloodhound fang", "curved greatsword", "bleed", "skill", "whole game"], startingClass: "Samurai", mechanic: "Skill damage", collection: "Other guides", availableFrom: "early",
    publishedStages: {
      early: sourcedStage("RL 25", "Bloodhound’s Fang", "Finger Seal after reaching 15 FAI", "Bloodhound’s Finesse", ["Green Turtle Talisman", "Radagon’s Soreseal"], "Land of Reeds Set; replace pieces only as needed to remain at medium load", ["Golden Vow (Ash of War before 25 FAI)"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "VIG 20, MND 11, END 13, STR 18, DEX 17; two-hand if using Radagon’s Soreseal as a temporary requirement bridge"),
      mid: sourcedStage("RL 50", "Bloodhound’s Fang", "Finger Seal", "Bloodhound’s Finesse", ["Green Turtle Talisman", "Radagon’s Soreseal", "Ritual Sword Talisman"], "Knight Set", ["Bloodflame Blade", "Flame, Grant Me Strength"], "Opaline Bubbletear + Greenburst Crystal Tear", "VIG 30, MND 11, END 13, STR 18, DEX 25, FAI 15; collect Greenburst only when the route reaches the Caelid Erdtree Avatar"),
      late: sourcedStage("RL 100–150", "Bloodhound’s Fang", "Frenzied Flame Seal only if Hyetta’s quest was selected; otherwise Finger Seal", "Bloodhound’s Finesse", ["Shard of Alexander", "Ritual Sword Talisman", "Ritual Shield Talisman", "Green Turtle Talisman"], "Skeletal Mask; Blaidd’s Armor and Gauntlets; Night’s Cavalry Greaves", ["Bloodflame Blade", "Flame, Grant Me Strength"], "Opaline Bubbletear + Greenburst Crystal Tear", "At RL100: VIG 40, END 20, STR 18, DEX 58, FAI 15. At RL150: VIG 50, END 25, STR 31, DEX 80"),
      dlc: sourcedStage("RL 150+", "Bloodhound’s Fang", "Frenzied Flame Seal or Finger Seal", "Bloodhound’s Finesse", ["Shard of Alexander", "Ritual Sword Talisman", "Ritual Shield Talisman", "Green Turtle Talisman"], "Skeletal Mask; Blaidd’s Armor and Gauntlets; Night’s Cavalry Greaves", ["Bloodflame Blade", "Flame, Grant Me Strength"], "Opaline Bubbletear + Greenburst Crystal Tear", "Keep the RL150 core: VIG 50, END 25, STR 31, DEX 80, FAI 15; add VIG/END for DLC comfort"),
    },
    source: { label: "Mobalytics: Bloodhound’s Fang Build Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-bloodhounds-fang-build" },
  },
  {
    id: "mobalytics-blasphemous-blade",
    name: "Blasphemous Blade Pilgrim",
    stats: "STR / FAI",
    role: "Melee",
    playstyle: "Taker’s Flames is the engine: the blade rises and a fire wave rolls along the ground, dealing heavy fire damage, flooring many enemies, and healing you for every target hit. Exploration stays cheap — greatsword swings cost no FP and every nearby death while the blade is equipped restores HP, so trash packs top you off without flasks. Before bosses drink the Flame-Shrouding Cracked Tear and cast Flame, Grant Me Strength at the fog: it lifts physical and fire but expires fast. The punish window is strict because the skill’s startup can be interrupted — land a stance-breaking jump or charged heavy, then release the wave into that knockdown so Shard of Alexander and Fire Scorpion Charm multiply it while Erdtree’s Favor and Dragoncrest Greatshield absorb the charm’s defense tax. When wounded, a connected Taker’s Flames beats a flask, since offense and healing land together. FP discipline matters because repeated casts outpace Mind — meter casts and melee between windows. Fire-resistant bosses are the ceiling: the wave withers and you fall back on physical swings.",
    complexity: "Published guide", phases: { early: "Lordsworn’s Greatsword", mid: "Lordsworn’s Greatsword", late: "Blasphemous Blade", dlc: "Blasphemous Blade" },
    tags: ["blasphemous blade", "greatsword", "faith", "fire", "healing"], startingClass: "Confessor", mechanic: "Skill damage", collection: "Other guides", availableFrom: "late", quest: "Defeat Rykard through the Volcano Manor dungeon after the route reaches Mt. Gelmir",
    publishedStages: {
      early: sourcedStage("RL 25", "Lordsworn’s Greatsword", "Finger Seal", "Square Off or Sacred Blade", ["Crimson Amber Medallion"], "Confessor Set; stay at medium load", ["Urgent Heal"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "VIG 20, END 11, STR 14, DEX 14, FAI 14"),
      mid: sourcedStage("RL 50", "Lordsworn’s Greatsword", "Finger Seal", "Sacred Blade", ["Two Fingers Heirloom", "Starscourge Heirloom"], "Knight Set at medium load", ["Flame, Grant Me Strength"], "Opaline Hardtear + Greenburst Crystal Tear", "VIG 29, END 11, STR 22, DEX 15, FAI 21"),
      late: sourcedStage("RL 100–150", "Blasphemous Blade", "Finger Seal", "Taker’s Flames", ["Shard of Alexander", "Fire Scorpion Charm", "Erdtree’s Favor", "Dragoncrest Greatshield Talisman"], "Ruler’s Mask, Crucible Axe Armor, Crucible Gauntlets, Crucible Greaves", ["Flame, Grant Me Strength"], "Flame-Shrouding Cracked Tear + Opaline Hardtear", "RL100: VIG 40, END 30, STR 30, DEX 15, FAI 33. RL150: VIG 40, END 30, STR 50, DEX 15, FAI 60"),
      dlc: sourcedStage("RL 150+", "Blasphemous Blade", "Finger Seal", "Taker’s Flames", ["Shard of Alexander", "Fire Scorpion Charm", "Erdtree’s Favor +2", "Dragoncrest Greatshield Talisman"], "Crucible Axe Set", ["Flame, Grant Me Strength"], "Flame-Shrouding Cracked Tear + Opaline Hardtear", "Keep the guide’s RL150 core; add VIG/MND before further damage stats"),
    },
    source: { label: "Mobalytics: Blasphemous Blade Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-blasphemous-blade-build" },
  },
  {
    id: "mobalytics-moonveil",
    name: "Moonveil Stancebreaker",
    stats: "DEX / INT",
    role: "Spellblade",
    playstyle: "Field play is katana lights, running slashes, and rolls — all FP-free — while Transient Moonlight waits for openings. The stance readies two follow-ups: a fast horizontal wave for groups, a slower vertical wave with more range and damage — both land hardest at blade-and-projectile range, where the katana supplies most stance damage. Against bosses, pre-cast Glintblade Phalanx or set Terra Magica, open with a heavy Transient Moonlight on the first recovery, chain heavies to force the break, then take the critical — Assassin’s Cerulean Dagger refunds that FP. The loadout is an FP economy: Carian Filigreed Crest trims skill cost, Shard of Alexander and Magic-Shrouding tear inflate the wave, Magic Scorpion Charm’s boost is offset by Dragoncrest Greatshield. Late game, Cerulean Hidden Tear buys free casts to spend inside Terra Magica. Every cast burns FP, so weave normals between waves and never fire from max range, wasting the blade’s stance share. Magic resistance is the ceiling: wave and sorceries fade together, leaving the katana’s physical half as the fallback.",
    complexity: "Published guide", phases: { early: "Uchigatana → Moonveil", mid: "Moonveil + Cold Uchigatana", late: "Moonveil + Carian Glintstone Staff", dlc: "Moonveil + Carian Glintstone Staff" },
    tags: ["moonveil", "katana", "intelligence", "stance", "sorcery"], startingClass: "Samurai", mechanic: "Stance damage", collection: "Other guides", availableFrom: "mid",
    publishedStages: {
      early: sourcedStage("RL 25 until Gael Tunnel", "Uchigatana", "Demi-Human Queen's Staff", "Unsheathe", ["Green Turtle Talisman"], "Land of Reeds Set; medium load", ["Glintstone Pebble"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "VIG 14, STR 12, DEX 15, INT 23; do not claim Moonveil until the planned Gael Tunnel fight"),
      mid: sourcedStage("RL 50", "Moonveil", "Cold Uchigatana + Glintblade Phalanx or Carian Glintstone Staff", "Transient Moonlight", ["Carian Filigreed Crest", "Assassin’s Cerulean Dagger", "Green Turtle Talisman"], "Knight Set", ["Carian Slicer", "Glintstone Pebble"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "VIG 30, MND 15, END 15, STR 12, DEX 18, INT 23"),
      late: sourcedStage("RL 100–150", "Moonveil", "Carian Glintstone Staff; Cold Uchigatana is optional", "Transient Moonlight", ["Shard of Alexander", "Magic Scorpion Charm", "Ritual Sword Talisman", "Dragoncrest Greatshield Talisman"], "Spellblade Set", ["Carian Slicer", "Terra Magica"], "Magic-Shrouding Cracked Tear + Cerulean Hidden Tear", "RL100: VIG 40, MND 20, END 20, DEX 20, INT 51. RL150: VIG 50, MND 20, END 20, DEX 50, INT 60"),
      dlc: sourcedStage("RL 150+", "Moonveil", "Carian Glintstone Staff", "Transient Moonlight", ["Shard of Alexander", "Magic Scorpion Charm", "Ritual Sword Talisman", "Dragoncrest Greatshield Talisman"], "Spellblade Set", ["Carian Slicer", "Terra Magica"], "Magic-Shrouding Cracked Tear + Cerulean Hidden Tear", "Keep INT 60 and DEX 50; add VIG/END before pushing damage"),
    },
    source: { label: "Mobalytics: Moonveil Build Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-moonveil-build" },
  },
  {
    id: "mobalytics-carian-spellblade",
    name: "Carian Sword Spellblade",
    stats: "STR / INT",
    role: "Spellblade",
    playstyle: "Fight at spell-melee range with the Carian Glintstone Staff off-hand: pre-cast Glintblade Phalanx before closing so delayed blades land as you arrive and bank stance damage toward a critical, answer short openings with the near-melee-speed, trivial-FP Carian Slicer, and hold charged Carian Grandeur for staggers, where the Knight’s Sword becomes a giant magic blade for its heaviest hit. Charged Carian Piercer covers approaching enemies or a downed boss. The loadout splits: Shard of Alexander boosts Grandeur, Graven-Mass lifts sorceries only, the staff adds its Carian-sorcery bonus to Slicer and Piercer, Radagon Icon speeds melee-range casts, and Cerulean Amber Medallion plus Stargazer Heirloom feed the FP and INT pools. Track both meters — casting, swinging, and dodging drain stamina, so never end a combo unable to roll; keep FP for sorceries, not just skills. The source delays Vigor early on purpose — respect spacing until RL50’s VIG 20. Magic resistance is the weakness: sword, Slicer, Piercer, and Grandeur fade together, so lean on physical pokes instead of forcing spells.",
    complexity: "Published guide", phases: { early: "Astrologer’s Staff + Carian Slicer", mid: "Carian Knight’s Sword + Carian Glintstone Staff", late: "Carian Knight’s Sword + Carian Glintstone Staff", dlc: "Carian Knight’s Sword + Carian Glintstone Staff" },
    tags: ["carian", "spellblade", "intelligence", "sorcery", "no shield"], startingClass: "Astrologer", mechanic: "Spell damage", collection: "Other guides", availableFrom: "early",
    publishedStages: {
      early: sourcedStage("RL 25", "Astrologer’s Staff", "No shield", "Carian Slicer", ["Crimson Amber Medallion"], "Astrologer starting armour at medium load", ["Carian Slicer", "Glintstone Pebble"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "MND 17, END 14, INT 28; the source intentionally delays Vigor here"),
      mid: sourcedStage("RL 50", "Carian Knight’s Sword", "Carian Glintstone Staff", "Carian Grandeur", ["Cerulean Amber Medallion", "Graven-School Talisman", "Radagon Icon"], "Astrologer starting armour", ["Carian Slicer", "Carian Piercer", "Glintblade Phalanx"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "Guide breakpoint: RL50 VIG 20, STR 18, INT 32"),
      late: sourcedStage("RL 100–150", "Carian Knight’s Sword", "Carian Glintstone Staff", "Carian Grandeur", ["Cerulean Amber Medallion", "Graven-Mass Talisman", "Shard of Alexander", "Stargazer Heirloom"], "Spellblade Set", ["Carian Slicer", "Carian Piercer", "Glintblade Phalanx"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "Guide breakpoints: RL100 VIG 31, MND 22, INT 60; RL150 VIG 40, MND 30, END 30, STR 21, INT 80"),
      dlc: sourcedStage("RL 150+", "Carian Knight’s Sword", "Carian Glintstone Staff", "Carian Grandeur", ["Cerulean Amber Medallion", "Graven-Mass Talisman", "Shard of Alexander", "Stargazer Heirloom"], "Spellblade Set", ["Carian Slicer", "Carian Piercer", "Glintblade Phalanx"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "Keep the guide's RL150 core: VIG 40, MND 30, END 30, STR 21, INT 80"),
    },
    source: { label: "Mobalytics: Spellblade Build Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-spellblade-build" },
  },
  {
    id: "game8-wing-stance-milady",
    name: "Wing Stance Milady",
    stats: "STR / DEX / FAI",
    role: "Melee",
    playstyle: "The kit is DLC-locked: two-handed Quality Milady +25 with Wing Stance turns lights into a rapid three-hit string of heavy poise damage chaining into itself as FP allows, and heavies into a leaping thrust that closes gaps, hops low sweeps, and deals real stance damage. Field work is stance lights into the jump thrust; guards fold without flasks. Boss prep is fixed: Golden Vow, the Stonebarb-plus-Thorny physick, Flame, Grant Me Strength last (it expires fastest), then hold Wing Stance so Rellana’s Cameo arms the release. Punish: hold stance through a recovery, release the string — Winged and Rotten Winged Sword Insignia stack power across hits — then add the jumping thrust until poise breaks for the critical. Mind 25 funds several full strings before a Cerulean flask; Endurance 30 keeps the medium roll; two-handing lifts STR 54 to an effective 81. Honest costs: pre-DLC phases borrow other builds until Castle Ensis, the Cameo hold gambles against fast bosses — release early rather than eat a hit — and with no shield or status plan beyond grease, chains drain FP fast.",
    complexity: "Published guide",
    phases: {
      early: "Sourced bridge until Milady",
      mid: "Sourced bridge until Milady",
      late: "Sourced bridge until Milady",
      dlc: "Quality Milady + Wing Stance",
    },
    tags: ["milady", "wing stance", "quality", "two-handed", "multi-hit", "no shield"],
    startingClass: "Samurai",
    mechanic: "Light attacks",
    collection: "Other guides",
    availableFrom: "dlc",
    phaseBridges: {
      early: "fextra-berserker",
      mid: "fextra-champion",
      late: "fextra-slumberingswordstress",
    },
    publishedLoadout: {
      level: "RL 150–192",
      weapon: "Quality Milady +25",
      offhand: "Finger Seal for buffs only; no shield",
      skill: "Wing Stance",
      talismans: ["Rellana's Cameo", "Winged Sword Insignia", "Rotten Winged Sword Insignia"],
      armour: "No specific armour required by the source; keep a medium roll",
      spells: ["Golden Vow", "Flame, Grant Me Strength"],
      flask: "Stonebarb Cracked Tear + Thorny Cracked Tear",
      stats: "VIG 60, MND 25, END 30, STR 54, DEX 60, INT 9, FAI 25, ARC 8 at RL 192; the source also gives an RL 150 starting point",
    },
    source: {
      label: "Game8: Wing Stance Milady Build Guide",
      url: "https://game8.co/games/Elden-Ring/archives/460059",
    },
  },
];
