import type { Build, StageLoadout } from "./data";

const sourcedStage = (level: string, weapon: string, offhand: string, skill: string, talismans: string[], armour: string, spells: string[], flask: string, stats: string): Omit<StageLoadout, "talismanSlots"> => ({ level, weapon, offhand, skill, talismans, armour, spells, flask, stats });

export const additionalSourcedBuilds: Build[] = [
  {
    id: "mobalytics-bloodhounds-fang",
    name: "Bloodhound’s Fang Finesse",
    stats: "STR / DEX / FAI",
    role: "Melee",
    playstyle: "Fight mobile and two-handed: jumping heavies supply damage and stance pressure, while Bloodhound’s Finesse leaps away before its optional dash-slash re-enters with invulnerability frames. Bloodflame Blade adds fire and delayed bleed buildup for a small Faith and Arcane investment, but raw physical damage and other weapon buffs still work against bleed-immune targets. The full skill sequence consumes FP and stamina, and careless repositioning can carry the player into a new attack.",
    complexity: "Published guide",
    phases: { early: "Uchigatana → Bloodhound’s Fang", mid: "Bloodhound’s Fang + Bloodflame Blade", late: "Bloodhound’s Fang + Finesse", dlc: "Bloodhound’s Fang + Finesse" },
    tags: ["bloodhound fang", "curved greatsword", "bleed", "skill", "whole game"], startingClass: "Samurai", mechanic: "Skill damage", collection: "Other guides", availableFrom: "early",
    publishedStages: {
      early: sourcedStage("RL 25", "Bloodhound’s Fang", "Finger Seal after reaching 15 FAI", "Bloodhound’s Finesse", ["Green Turtle Talisman", "Radagon’s Soreseal"], "Land of Reeds Set; replace pieces only as needed to remain at medium load", ["Golden Vow (Ash of War before 25 FAI)"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "VIG 20, MND 11, END 13, STR 18, DEX 17; two-hand if using Radagon’s Soreseal as a temporary requirement bridge"),
      mid: sourcedStage("RL 50", "Bloodhound’s Fang", "Finger Seal", "Bloodhound’s Finesse", ["Green Turtle Talisman", "Radagon’s Soreseal", "Ritual Sword Talisman"], "Knight Set", ["Bloodflame Blade", "Flame, Grant Me Strength"], "Opaline Bubbletear + Greenburst Crystal Tear", "VIG 30, MND 11, END 13, STR 18, DEX 25, FAI 15; collect Greenburst only when the route reaches the Caelid Erdtree Avatar"),
      late: sourcedStage("RL 100–150", "Bloodhound’s Fang", "Frenzied Flame Seal only if Hyetta’s quest was selected; otherwise Finger Seal", "Bloodhound’s Finesse", ["Shard of Alexander", "Ritual Sword Talisman", "Ritual Shield Talisman", "Green Turtle Talisman"], "Skeletal Mask; Blaidd’s Armor and Gauntlets; Night’s Cavalry Greaves", ["Bloodflame Blade", "Flame, Grant Me Strength"], "Opaline Bubbletear + Greenburst Crystal Tear", "At RL100: VIG 40, END 20, STR 18, DEX 58, FAI 15. At RL150: VIG 50, END 25, STR 31, DEX 80"),
      dlc: sourcedStage("RL 150+", "Bloodhound’s Fang", "Frenzied Flame Seal or Finger Seal", "Bloodhound’s Finesse", ["Shard of Alexander", "Ritual Sword Talisman", "Ritual Shield Talisman", "Green Turtle Talisman"], "Skeletal Mask; Blaidd’s Armor and Gauntlets; Night’s Cavalry Greaves", ["Bloodflame Blade", "Flame, Grant Me Strength"], "Opaline Bubbletear + Greenburst Crystal Tear", "Keep the RL150 core: VIG 50, END 25, STR 31, DEX 80, FAI 15; add VIG/END for DLC comfort"),
    },
    source: { label: "Mobalytics: Bloodhound’s Fang Build Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-bloodhounds-fang-build" },
  },
  {
    id: "mobalytics-blasphemous-blade",
    name: "Blasphemous Blade Pilgrim",
    stats: "STR / FAI",
    role: "Melee",
    playstyle: "Build the run around Taker’s Flames, a ground-travelling fire wave that deals heavy damage, knocks down vulnerable enemies and restores health for every target hit. Cast Golden Vow and Flame, Grant Me Strength before bosses, use ordinary greatsword attacks when spending FP is unnecessary, and let the blade’s heal on nearby deaths sustain exploration. The sword is unavailable until Rykard falls, its startup can be interrupted, and fire-resistant targets force a return to physical melee.",
    complexity: "Published guide", phases: { early: "Lordsworn’s Greatsword", mid: "Lordsworn’s Greatsword", late: "Blasphemous Blade", dlc: "Blasphemous Blade" },
    tags: ["blasphemous blade", "greatsword", "faith", "fire", "healing"], startingClass: "Confessor", mechanic: "Skill damage", collection: "Other guides", availableFrom: "late", quest: "Defeat Rykard through the Volcano Manor dungeon after the route reaches Mt. Gelmir",
    publishedStages: {
      early: sourcedStage("RL 25", "Lordsworn’s Greatsword", "Finger Seal", "Square Off or Sacred Blade", ["Crimson Amber Medallion"], "Confessor Set; stay at medium load", ["Urgent Heal"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "VIG 20, END 11, STR 14, DEX 14, FAI 14"),
      mid: sourcedStage("RL 50", "Lordsworn’s Greatsword", "Finger Seal", "Sacred Blade", ["Two Fingers Heirloom", "Starscourge Heirloom"], "Knight Set at medium load", ["Flame, Grant Me Strength"], "Opaline Hardtear + Greenburst Crystal Tear", "VIG 29, END 11, STR 22, DEX 15, FAI 21"),
      late: sourcedStage("RL 100–150", "Blasphemous Blade", "Finger Seal", "Taker’s Flames", ["Shard of Alexander", "Fire Scorpion Charm", "Erdtree’s Favor", "Dragoncrest Greatshield Talisman"], "Ruler’s Mask, Crucible Axe Armor, Crucible Gauntlets, Crucible Greaves", ["Flame, Grant Me Strength"], "Flame-Shrouding Cracked Tear + Opaline Hardtear", "RL100: VIG 40, END 30, STR 30, DEX 15, FAI 33. RL150: VIG 40, END 30, STR 50, DEX 15, FAI 60"),
      dlc: sourcedStage("RL 150+", "Blasphemous Blade", "Finger Seal", "Taker’s Flames", ["Shard of Alexander", "Fire Scorpion Charm", "Erdtree’s Favor +2", "Dragoncrest Greatshield Talisman"], "Crucible Axe Set", ["Flame, Grant Me Strength"], "Flame-Shrouding Cracked Tear + Opaline Hardtear", "Keep the guide’s RL150 core; add VIG/MND before further damage stats"),
    },
    source: { label: "Mobalytics: Blasphemous Blade Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-blasphemous-blade-build" },
  },
  {
    id: "mobalytics-moonveil",
    name: "Moonveil Stancebreaker",
    stats: "DEX / INT",
    role: "Spellblade",
    playstyle: "Alternate katana pressure with Transient Moonlight: the light follow-up is a quick horizontal wave for groups, while the heavy sends a stronger vertical wave through longer openings. Cast at close range when possible so the blade and projectile both connect, because the blade contributes most of the stance damage. Supporting sorceries preload stance pressure or cover range, but repeated skill use drains FP quickly and magic-resistant enemies blunt the whole kit.",
    complexity: "Published guide", phases: { early: "Uchigatana → Moonveil", mid: "Moonveil + Cold Uchigatana", late: "Moonveil + Carian Glintstone Staff", dlc: "Moonveil + Carian Glintstone Staff" },
    tags: ["moonveil", "katana", "intelligence", "stance", "sorcery"], startingClass: "Samurai", mechanic: "Stance damage", collection: "Other guides", availableFrom: "mid",
    publishedStages: {
      early: sourcedStage("RL 25 until Gael Tunnel", "Uchigatana", "Demi-Human Queen's Staff", "Unsheathe", ["Green Turtle Talisman"], "Land of Reeds Set; medium load", ["Glintstone Pebble"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "VIG 14, STR 12, DEX 15, INT 23; do not claim Moonveil until the planned Gael Tunnel fight"),
      mid: sourcedStage("RL 50", "Moonveil", "Cold Uchigatana + Glintblade Phalanx or Carian Glintstone Staff", "Transient Moonlight", ["Carian Filigreed Crest", "Assassin’s Cerulean Dagger", "Green Turtle Talisman"], "Knight Set", ["Carian Slicer", "Glintstone Pebble"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "VIG 30, MND 15, END 15, STR 12, DEX 18, INT 23"),
      late: sourcedStage("RL 100–150", "Moonveil", "Carian Glintstone Staff; Cold Uchigatana is optional", "Transient Moonlight", ["Shard of Alexander", "Magic Scorpion Charm", "Ritual Sword Talisman", "Dragoncrest Greatshield Talisman"], "Spellblade Set", ["Carian Slicer", "Terra Magica"], "Magic-Shrouding Cracked Tear + Cerulean Hidden Tear", "RL100: VIG 40, MND 20, END 20, DEX 20, INT 51. RL150: VIG 50, MND 20, END 20, DEX 50, INT 60"),
      dlc: sourcedStage("RL 150+", "Moonveil", "Carian Glintstone Staff", "Transient Moonlight", ["Shard of Alexander", "Magic Scorpion Charm", "Ritual Sword Talisman", "Dragoncrest Greatshield Talisman"], "Spellblade Set", ["Carian Slicer", "Terra Magica"], "Magic-Shrouding Cracked Tear + Cerulean Hidden Tear", "Keep INT 60 and DEX 50; add VIG/END before pushing damage"),
    },
    source: { label: "Mobalytics: Moonveil Build Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-moonveil-build" },
  },
  {
    id: "mobalytics-carian-spellblade",
    name: "Carian Sword Spellblade",
    stats: "STR / INT",
    role: "Spellblade",
    playstyle: "Cast delayed glintblades before closing, answer short openings with the fast Carian Slicer and reserve a charged Carian Grandeur for a larger punish. An off-hand Carian Glintstone Staff strengthens the sword-sorcery half while Intelligence feeds both casting and the Carian Knight’s Sword. Fighting at spell-melee range demands constant FP and stamina control, and magic resistance weakens every major damage option at once.",
    complexity: "Published guide", phases: { early: "Astrologer’s Staff + Carian Slicer", mid: "Carian Knight’s Sword + Carian Glintstone Staff", late: "Carian Knight’s Sword + Carian Glintstone Staff", dlc: "Carian Knight’s Sword + Carian Glintstone Staff" },
    tags: ["carian", "spellblade", "intelligence", "sorcery", "no shield"], startingClass: "Astrologer", mechanic: "Spell damage", collection: "Other guides", availableFrom: "early",
    publishedStages: {
      early: sourcedStage("RL 25", "Astrologer’s Staff", "No shield", "Carian Slicer", ["Crimson Amber Medallion"], "Astrologer starting armour at medium load", ["Carian Slicer", "Glintstone Pebble"], "Opaline Bubbletear + Crimsonburst Crystal Tear", "MND 17, END 14, INT 28; the source intentionally delays Vigor here"),
      mid: sourcedStage("RL 50", "Carian Knight’s Sword", "Carian Glintstone Staff", "Carian Grandeur", ["Cerulean Amber Medallion", "Graven-School Talisman", "Radagon Icon"], "Astrologer starting armour", ["Carian Slicer", "Carian Piercer", "Glintblade Phalanx"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "Guide breakpoint: RL50 VIG 20, STR 18, INT 32"),
      late: sourcedStage("RL 100–150", "Carian Knight’s Sword", "Carian Glintstone Staff", "Carian Grandeur", ["Cerulean Amber Medallion", "Graven-Mass Talisman", "Shard of Alexander", "Stargazer Heirloom"], "Spellblade Set", ["Carian Slicer", "Carian Piercer", "Glintblade Phalanx"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "Guide breakpoints: RL100 VIG 31, MND 22, INT 60; RL150 VIG 40, MND 30, END 30, STR 21, INT 80"),
      dlc: sourcedStage("RL 150+", "Carian Knight’s Sword", "Carian Glintstone Staff", "Carian Grandeur", ["Cerulean Amber Medallion", "Graven-Mass Talisman", "Shard of Alexander", "Stargazer Heirloom"], "Spellblade Set", ["Carian Slicer", "Carian Piercer", "Glintblade Phalanx"], "Magic-Shrouding Cracked Tear + Intelligence-knot Crystal Tear", "Keep the guide's RL150 core: VIG 40, MND 30, END 30, STR 21, INT 80"),
    },
    source: { label: "Mobalytics: Spellblade Build Guide", url: "https://mobalytics.gg/gamebase/guides/elden-ring-spellblade-build" },
  },
  {
    id: "game8-wing-stance-milady",
    name: "Wing Stance Milady",
    stats: "STR / DEX / FAI",
    role: "Melee",
    playstyle: "Two-hand a Quality Milady and remain ready in Wing Stance: its three-hit light string can repeat for pressure or chain into a leaping thrust that closes distance and deals heavier poise damage. Golden Vow, Flame, Grant Me Strength and the Stonebarb/Thorny Physick front-load the boss setup, while Rellana’s Cameo rewards holding the stance before release. The complete kit is DLC-only, has no shield or status plan, and burns FP quickly when stance attacks are chained.",
    complexity: "Published guide",
    phases: {
      early: "Sourced bridge until Milady",
      mid: "Sourced bridge until Milady",
      late: "Sourced bridge until Milady",
      dlc: "Quality Milady + Wing Stance",
    },
    tags: ["milady", "wing stance", "quality", "two-handed", "multi-hit", "no shield"],
    startingClass: "Samurai",
    mechanic: "Light attacks",
    collection: "Other guides",
    availableFrom: "dlc",
    phaseBridges: {
      early: "fextra-berserker",
      mid: "fextra-champion",
      late: "fextra-slumberingswordstress",
    },
    publishedLoadout: {
      level: "RL 150–192",
      weapon: "Quality Milady +25",
      offhand: "Finger Seal for buffs only; no shield",
      skill: "Wing Stance",
      talismans: ["Rellana's Cameo", "Winged Sword Insignia", "Rotten Winged Sword Insignia"],
      armour: "No specific armour required by the source; keep a medium roll",
      spells: ["Golden Vow", "Flame, Grant Me Strength"],
      flask: "Stonebarb Cracked Tear + Thorny Cracked Tear",
      stats: "VIG 60, MND 25, END 30, STR 54, DEX 60, INT 9, FAI 25, ARC 8 at RL 192; the source also gives an RL 150 starting point",
    },
    source: {
      label: "Game8: Wing Stance Milady Build Guide",
      url: "https://game8.co/games/Elden-Ring/archives/460059",
    },
  },
];
